export const skills = [
    "Semantic & accessible HTML",
    "Responsive Web Design",
    "Markdown",
    "JavaScript ES6+",
    "Immutability",
    "CSS BEM convention",
    "CSS Grid",
    "CSS Flexbox",
    "React",
    "React Hooks",
    "React Router",
    "Redux-Saga",
    "Redux (Toolkit)",
    "Error handling",
    "Promises, Async/Await",
    "NPM",
    "Git",
    "Trello",
    "Teamwork",
    "Scrum",
    "Figma",
    "Working with API (fetch, axios)",
    "GitHub Pull Requests & Review",
  ];
  
  export const toLearn = [
    "React",
    "Vanilla JS",
    "Node.js",
    "TypeScript",
    "JS classes",
    "CSS",
  ];